# Generated by Django 5.0.7 on 2024-09-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('appointment_date', models.DateTimeField()),
                ('specialization', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
            ],
        ),
    ]
